FROM node:12-alpine

# Create a non-root user
RUN groupadd --gid 1001 apiuser && useradd --uid 1001 --gid 1001 -m apiuser

# Set working directory
WORKDIR /usr/src/app

# Change ownership of the app directory to the new user
RUN chown -R apiuser:apiuser /usr/src/app

# Switch to non-root user
USER apiuser

# Copy files and install dependencies
COPY package*.json ./
RUN npm install

COPY server.js ./

# Run Node.js application as non-root
CMD ["node", "server.js"]
